{% set name = "requests-scitokens" %}
{% set version = "0.2.0" %}
{% set python_min = python_min|default('0.1a0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/requests-scitokens/requests_scitokens-{{ version }}.tar.gz
  sha256: 99eb2b53de310a694a3d2040ebc580d8fa2938706bba7886db356e6c8fe1bcbe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=7
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.20.0
    - scitokens >=1.7.4

test:
  requires:
    - pip
    - pytest >=3.9.1
    - python {{ python_min }}
    - requests-mock
  commands:
    - python -m pip check
    - python -m pip show requests-scitokens
    - python -m pytest -ra -v --pyargs requests_scitokens

about:
  home: https://git.ligo.org/computing/software/requests-scitokens
  dev_url: https://git.ligo.org/computing/software/requests-scitokens
  doc_url: https://requests-scitokens.readthedocs.io/
  summary: A requests plugin for SciToken authorisation
  description: |
    `requests-scitokens` provides an authentication plugin for
    [Requests](http://requests.readthedocs.io/) that handles attaching
    [SciTokens](https://scitokens.org) to HTTP requests.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
